---
# install ant for build
  - name: Download Apache Ant
    get_url: url=http://mirror.cc.columbia.edu/pub/software/apache//ant/binaries/apache-ant-{{ ant_version }}-bin.tar.bz2 dest=/tmp/apache-ant-{{ ant_version }}-bin.tar.bz2
  - name: Untar Ant
    shell: chdir=/tmp creates=/opt/apache-ant-{{ ant_version }} tar -jxf apache-ant-{{ ant_version }}-bin.tar.bz2 -C /opt
  - lineinfile: dest=/etc/profile regexp='^#?\s*export ANT_HOME=(.*)$' line='export ANT_HOME=/opt/apache-ant-{{ ant_version }}' state=present
  - lineinfile: dest=/etc/profile regexp='^#?\s*export PATH=(.*)ANT_HOME(.*)$' line="export PATH=$PATH:$ANT_HOME/bin" state=present
